CREATE TABLE sensor (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(100) NOT NULL,
  latitude    NUMERIC(9,6) CHECK (latitude BETWEEN -90 AND 90),
  longitude   NUMERIC(9,6) CHECK (longitude BETWEEN -180 AND 180),
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uk_sensor_name ON sensor (lower(name));